version: '3'
services:
    web:
        image: nginx
        container_name: cev-web
        volumes:
            - ./www:/var/www
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf            
        ports:
            - 8000:80
        restart: unless-stopped
        depends_on:
            - php
            - db
        networks:
            - cev
    php:
        build: .docker
        restart: always
        container_name: cev-app
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            # - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            -  ./www:/var/www
        networks:
            - cev
    db:
        image: postgres:11-alpine
        container_name: cev-db
        restart: always
        environment:
            POSTGRES_USER: dba
            POSTGRES_PASSWORD: sql
        ports:
            - 5555:5432
        volumes:
            #Persistir datos
            - ./postgres-data:/var/lib/postgresql/data        
        networks:
            - cev
networks:
  cev:
    driver: bridge
