
-- Corrección al excel
insert into catalogos.cat_item (id_cat,descripcion,otro) values(85,'Ojetivo: Convivencia','ia_ds_o_convivencia');
insert into catalogos.cat_item (id_cat,descripcion,otro) values(85,'Objetivo: Reconocimiento','ia_ds_o_reconocimiento');
insert into catalogos.cat_item (id_cat,descripcion,otro) values(85,'Objetivo: No Repetición','ia_ds_o_no_repeticion');


-- Nueva tabla
drop table if exists esclarecimiento.excel_entrevista_fvt;

-- Nueva tabla
drop table if exists esclarecimiento.excel_entrevista_fvt;
create table esclarecimiento.excel_entrevista_fvt
(
    id_e_ind_fvt                integer      not null
        constraint excel_entrevista_fvt_pkey
            primary key,
    correlativo                 integer,
    clasificacion                 integer default 3,
    codigo_entrevista           text,
    codigo_entrevistador        text,
    macroterritorio_id          integer,
    macroterritorio_txt         text,
    territorio_id               integer,
    territorio_txt              text,
    grupo_id                    integer,
    grupo_txt                   text,
    entrevista_fecha            text,
    entrevista_lugar_n1_codigo  text,
    entrevista_lugar_n1_txt     text,
    entrevista_lugar_n2_codigo  text,
    entrevista_lugar_n2_txt     text,
    entrevista_lugar_n3_codigo  text,
    entrevista_lugar_n3_txt     text,
    titulo                      text,
    hechos_lugar_n1_codigo      text,
    hechos_lugar_n1_txt         text,
    hechos_lugar_n2_codigo      text,
    hechos_lugar_n2_txt         text,
    hechos_lugar_n3_codigo      text,
    hechos_lugar_n3_txt         text,
    hechos_del                  text,
    hechos_al                   text,
    anotaciones                 text,
    es_prioritario              integer default 0,
    prioritario_tema            text,
    sector_victima              text,
    interes_etnico              text,
    remitido                    text,
    transcrita                  text,
    aa_paramilitar              integer default 0,
    aa_guerrilla                integer default 0,
    aa_fuerza_publica           integer default 0,
    aa_terceros_civiles         integer default 0,
    aa_otro_grupo_armado        integer default 0,
    aa_otro_agente_estado       integer default 0,
    aa_otro_actor               integer default 0,
    aa_ns_nr                    integer default 0,
    aa_internacional            integer default 0,
    viol_homicidio              integer default 0,
    viol_atentado_vida          integer default 0,
    viol_amenaza_vida           integer default 0,
    viol_desaparicion_f         integer default 0,
    viol_tortura                integer default 0,
    viol_violencia_sexual       integer default 0,
    viol_esclavitud             integer default 0,
    viol_reclutamiento          integer default 0,
    viol_detencion_arbitraria   integer default 0,
    viol_secuestro              integer default 0,
    viol_confinamiento          integer default 0,
    viol_pillaje                integer default 0,
    viol_extorsion              integer default 0,
    viol_ataque_bien_protegido  integer default 0,
    viol_ataque_indiscriminado  integer default 0,
    viol_despojo_tierras        integer default 0,
    viol_desplazamiento_forzado integer default 0,
    viol_exilio                 integer default 0,
    i_objetivo_esclarecimiento  integer default 0,
    i_objetivo_reconocimiento   integer default 0,
    i_objetivo_convivencia      integer default 0,
    i_objetivo_no_repeticion    integer default 0,
    i_enfoque_genero            integer default 0,
    i_enfoque_psicosocial       integer default 0,
    i_enfoque_curso_vida        integer default 0,
    i_direccion_investigacion   integer default 0,
    i_direccion_territorios     integer default 0,
    i_direccion_etnica          integer default 0,
    i_comisionados              integer default 0,
    i_estrategia_arte           integer default 0,
    i_estrategia_comunicacion   integer default 0,
    i_estrategia_participacion  integer default 0,
    i_estrategia_pedagogia      integer default 0,
    i_grupo_acceso_informacion  integer default 0,
    i_presidencia               integer default 0,
    i_otra                      integer default 0,
    i_enlace                    integer default 0,
    i_sistema_informacion       integer default 0,
    ia_pueblo_etnico            integer default 0,
    ia_dialogo_social           integer default 0,
    ia_ds_o_convivencia           integer default 0,
    ia_ds_o_reconocimiento           integer default 0,
    ia_ds_o_no_repeticion           integer default 0,
    ia_genero                   integer default 0,
    ia_enfoque_ps               integer default 0,
    ia_curso_vida               integer default 0,
    nucleo_01                   integer default 0,
    nucleo_02                   integer default 0,
    nucleo_03                   integer default 0,
    nucleo_04                   integer default 0,
    nucleo_05                   integer default 0,
    nucleo_06                   integer default 0,
    nucleo_07                   integer default 0,
    nucleo_08                   integer default 0,
    nucleo_09                   integer default 0,
    nucleo_10                   integer default 0,
    mandato_01                  integer default 0,
    mandato_02                  integer default 0,
    mandato_03                  integer default 0,
    mandato_04                  integer default 0,
    mandato_05                  integer default 0,
    mandato_06                  integer default 0,
    mandato_07                  integer default 0,
    mandato_08                  integer default 0,
    mandato_09                  integer default 0,
    mandato_10                  integer default 0,
    mandato_11                  integer default 0,
    mandato_12                  integer default 0,
    mandato_13                  integer default 0,
    dinamica_1                  text,
    dinamica_2                  text,
    dinamica_3                  text,
    a_consentimiento            text    default '0'::text,
    a_audio                     text    default '0'::text,
    a_ficha_corta               text    default '0'::text,
    a_ficha_larga               text    default '0'::text,
    a_otros                     text    default '0'::text,
    a_transcripcion_preliminar  text    default '0'::text,
    a_transcripcion_final       text    default '0'::text,
    a_retroalimentacion         text    default '0'::text,
    entrevista_lat              double precision,
    entrevista_lon              double precision,
    hechos_lat                  double precision,
    hechos_lon                  double precision,
    transcripcion_html          text,
    created_at                  timestamp(0) not null,
    updated_at                  timestamp(0) not null
);

alter table esclarecimiento.excel_entrevista_fvt
    owner to dba;

GRANT SELECT ON esclarecimiento.excel_entrevista_fvt TO solo_lectura;

