INSERT INTO "catalogos"."cat_cat" ("id_cat", "nombre", "descripcion", "editable") VALUES (34, 'Rango (grupo) del responsable individual', 'usado en el inciso 8', 1);
INSERT INTO "catalogos"."cat_cat" ("id_cat", "nombre", "descripcion", "editable") VALUES (35, 'Rango (cargo) del responsable individual', 'usado en el inciso 8', 1);

insert into catalogos.cat_item (id_cat,descripcion) values(34,'Grupo paramilitar');
insert into catalogos.cat_item (id_cat,descripcion) values(34,'Guerrilas');
insert into catalogos.cat_item (id_cat,descripcion) values(34,'Fuerza pública');

-- OJO buscar el ID del catalogo 34 para colocarlo en otro
-- paras
insert into catalogos.cat_item (id_cat,descripcion,otro) values(35,'Comandante',0);
insert into catalogos.cat_item (id_cat,descripcion,otro) values(35,'Combatiente',0);
insert into catalogos.cat_item (id_cat,descripcion,otro) values(35,'Urbano',0);
-- guerrilas
insert into catalogos.cat_item (id_cat,descripcion,otro) values(35,'Comandante',0);
insert into catalogos.cat_item (id_cat,descripcion,otro) values(35,'Combatiente',0);
insert into catalogos.cat_item (id_cat,descripcion,otro) values(35,'Miliciano',0);
-- fuerza publica
insert into catalogos.cat_item (id_cat,descripcion,otro) values(35,'Oficial',0);
insert into catalogos.cat_item (id_cat,descripcion,otro) values(35,'Suboficial',0);
insert into catalogos.cat_item (id_cat,descripcion,otro) values(35,'Soldado',0);



INSERT INTO "catalogos"."cat_cat" ("id_cat", "nombre", "descripcion", "editable") VALUES (36, 'Responsabilidad en los hechos', 'usado en el inciso 9 de responsable individual', 1);
insert into catalogos.cat_item (id_cat,descripcion) values(36,'La persona ORDENÓ el/los hechos');
insert into catalogos.cat_item (id_cat,descripcion) values(36,'La persona PLANEÓ el/los hechos');
insert into catalogos.cat_item (id_cat,descripcion) values(36,'La persona REALIZÓ el/los hechos');
insert into catalogos.cat_item (id_cat,descripcion) values(36,'La persona PARTICIPÓ el/los hechos');
insert into catalogos.cat_item (id_cat,descripcion) values(36,'La persona NO ACTUÓ PARA EVITAR que se comietieran los hechos');


--  Idiomas nativos
delete from catalogos.cat_item where id_cat=23;
insert into catalogos.cat_item (id_cat,descripcion) values (23,'ACHAGUA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'ANDOQUE');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'AWAPIT');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'BARÁ');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'BARASANA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'BARI');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'BORA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'CABIYARI');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'CACUA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'CARIJONA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'CHIMILA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'COCAMA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'COFÁN');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'CREOLE');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'CUBEO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'CUIBA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'DESANO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'EMBERA CHAMI');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'EMBERA DOBIDA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'EMBERA KATIO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'Gitanos-Rom');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'GUAYABERO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'HITNU');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'IKA ARHUACO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'INGA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'KAMSÁ');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'KARAPANA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'KOGUI');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'KOREGUAJE');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'KUNA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'KURRIPACO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'MAKUNA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'MIRAÑA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'MUINANE');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'NAMTRIK');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'NASA YUWE');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'NONUYA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'NUKAK');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'OCAINA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'PALENQUE');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'PIAPOCO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'PIAROA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'PIRATAPUYO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'PISAMIRA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'PUINAVE');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'SÁLIBA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'SIKUANI');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'SIONA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'SIRIANO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'TAIWANO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'TANIMUKA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'TARIANO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'TATUYO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'TIKUNA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'TINIGUA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'TUKANO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'TUYUCA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'UITOTO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'U''WA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'WANANO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'WAUNANA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'WAYUUNAIKI');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'WIWA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'YAGUA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'YARURO');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'YUCUNA');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'YUHUP');
insert into catalogos.cat_item (id_cat,descripcion) values (23,'YURUTI');


-- Pueblos indígenas
delete from catalogos.cat_item where id_cat=28;
insert into catalogos.cat_item (id_cat,descripcion) values (28,'ACHAGUA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'AMBALÓ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'AMORÚA ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'ANDOKE');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'ARHUACO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'AWÁ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'BARÁ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'BARASANA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'BARÍ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'BETOYE');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'BORA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'CARAPANA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'CHIRICOA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'COCAMA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'COREGUAJE');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'CURRIPAKO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'KARIJONA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'DESANO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'EMBERA CHAMÍ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'EMBERA DÓBIDA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'EMBERA KATÍO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'EPERARA-SIAPIDARA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'ETT E‘NEKA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'GUANACA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'GUANE');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'GUNA DULE');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'HITNU');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'HUPDë-HUPDAH-HUPDU');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'IJKU');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'INGA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'JIW');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'JUDPA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'JUHUP-YUJU');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'KAKUA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'KAMËNTŠÁ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'KANKUAMO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'KOFÁN');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'KOGUI');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'KAWIYARÍ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'KUBEO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'KOKONUKO  ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'LETUAMA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'MAKAGUAJE');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'MAPAYERRI');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'MATAPÍ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'MIRAÑA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'MASIGUARE');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'MAKUMA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'MISAK');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'MOKANÁ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'MUINA MURUI');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'MUISCA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'NASA ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'NUKAK');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'NONUYA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'PASTOS');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'PIAPOCO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'PIAROA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'PIJAO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'PIRATAPUYO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'POLINDARA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'PUBENSE');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'PISAMIRA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'PUINAVE');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'QUICHUA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'QUILLACINGA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'QUIZGÓ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'SÁLIBA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'SIKUANI / GUAHIBO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'SIONA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'TANIMUKA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'TIKUNA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'TAIWANO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'TAMA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'TANIGUA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'TATUYO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'TSIRIPU');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'TUBU / SIRIANO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'TOTORÓ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'TUYUKA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'TUCANO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'U''WA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'UITOTO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'WAMONAE / COIBA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'WANANO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'WAYUU');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'WIPIJIKI');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'WIWA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'WAUNAN');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'YAGUA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'YAMALERO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'YARI');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'YAUNA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'YARURO');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'YERAL');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'YANACONA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'YURI');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'YURUTÍ');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'YUKUNA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'YUKPA');
insert into catalogos.cat_item (id_cat,descripcion) values (28,'ZENÚ');

