drop table esclarecimiento.excel_entrevista_pr;
create table esclarecimiento.excel_entrevista_pr
(
	id_entrevista_profundidad integer not null
		constraint excel_entrevista_pr_pkey
			primary key,
	correlativo integer,
	clasificacion integer default 3,
	tipo_entrevista    text,
	codigo_entrevista text,
	codigo_entrevistador text,
	macroterritorio_id integer,
	macroterritorio_txt text,
	territorio_id integer,
	territorio_txt text,
	grupo_id integer,
	grupo_txt text,
	entrevista_fecha_inicio text,
	entrevista_fecha_final text,
	entrevista_avance_codigo text,
	entrevista_avance_txt text,
	tiempo_entrevista text,
	entrevista_lugar_n1_codigo text,
	entrevista_lugar_n1_txt text,
	entrevista_lugar_n2_codigo text,
	entrevista_lugar_n2_txt text,
	entrevista_lugar_n3_codigo text,
	entrevista_lugar_n3_txt text,
	titulo text,
	objetivo text,
	entrevistado_nombres text,
	entrevistado_apellidos text,
	sector_entrevistado text,
	anotaciones text,
	remitido text,
	transcrita text,
	tema_1 text,
	tema_2 text,
	tema_3 text,
	tema_4 text,
	tema_5 text,
	i_objetivo_esclarecimiento integer default 0,
	i_objetivo_reconocimiento integer default 0,
	i_objetivo_convivencia integer default 0,
	i_objetivo_no_repeticion integer default 0,
	i_enfoque_genero integer default 0,
	i_enfoque_psicosocial integer default 0,
	i_enfoque_curso_vida integer default 0,
	i_direccion_investigacion integer default 0,
	i_direccion_territorios integer default 0,
	i_direccion_etnica integer default 0,
	i_comisionados integer default 0,
	i_estrategia_arte integer default 0,
	i_estrategia_comunicacion integer default 0,
	i_estrategia_participacion integer default 0,
	i_estrategia_pedagogia integer default 0,
	i_grupo_acceso_informacion integer default 0,
	i_presidencia integer default 0,
	i_otra integer default 0,
	i_enlace integer default 0,
	i_sistema_informacion integer default 0,
	ia_pueblo_etnico integer default 0,
	ia_dialogo_social integer default 0,
	ia_ds_o_convivencia integer default 0,
	ia_ds_o_reconocimiento integer default 0,
	ia_ds_o_no_repeticion integer default 0,
	ia_genero integer default 0,
	ia_enfoque_ps integer default 0,
	ia_curso_vida integer default 0,
	nucleo_01 integer default 0,
	nucleo_02 integer default 0,
	nucleo_03 integer default 0,
	nucleo_04 integer default 0,
	nucleo_05 integer default 0,
	nucleo_06 integer default 0,
	nucleo_07 integer default 0,
	nucleo_08 integer default 0,
	nucleo_09 integer default 0,
	nucleo_10 integer default 0,
	mandato_01 integer default 0,
	mandato_02 integer default 0,
	mandato_03 integer default 0,
	mandato_04 integer default 0,
	mandato_05 integer default 0,
	mandato_06 integer default 0,
	mandato_07 integer default 0,
	mandato_08 integer default 0,
	mandato_09 integer default 0,
	mandato_10 integer default 0,
	mandato_11 integer default 0,
	mandato_12 integer default 0,
	mandato_13 integer default 0,
	dinamica_1 text,
	dinamica_2 text,
	dinamica_3 text,
	a_consentimiento integer default 0,
	a_audio integer default 0,
	a_ficha_corta integer default 0,
	a_ficha_larga integer default 0,
	a_otros integer default 0,
	a_transcripcion_preliminar integer default 0,
	a_transcripcion_final integer default 0,
	a_retroalimentacion integer default 0,
	a_relatoria integer default 0,
	a_certificacion_inicial integer default 0,
	a_certificacion_final integer default 0,
	a_plan_trabajo integer default 0,
	a_valoracion integer default 0,
	entrevista_lat double precision,
	entrevista_lon double precision,
	transcripcion_html text,
	created_at timestamp(0) not null,
	updated_at timestamp(0),
	id_entrevistador integer
);

alter table esclarecimiento.excel_entrevista_pr owner to dba;
GRANT SELECT ON esclarecimiento.excel_entrevista_pr TO solo_lectura;



create index excel_entrevista_pr_entrevista_index
	on esclarecimiento.excel_entrevista_pr (codigo_entrevista);

create index excel_entrevista_pr_id_entrevistador_index
	on esclarecimiento.excel_entrevista_pr (id_entrevistador);

