INSERT INTO catalogos.criterio_fijo (id_grupo, id_opcion, descripcion, orden) VALUES (22, 107, 'Clasificador NVIVO', DEFAULT);

drop table if exists public.metadatos_nvivo;
create table if not exists public.metadatos_nvivo
(
    codigo_entrevista varchar(20)
        constraint metadatos_nvivo_pkey
            primary key,
    tipo_entrevista varchar(100),
    personas_entrevistadas integer default 1,
    es_virtual varchar(5) default 'No',
    nivel_de_acceso integer default 3,
    macroterritorio text,
    territorio text,
    codigo_entrevistador text,
    grupo_entrevistador text,
    entrevista_fecha varchar(20),
    entrevista_mes varchar(20),
    entrevista_anyo varchar(20),
    tiempo_entrevista varchar(20) default 'No',
    entrevista_lugar_n1 varchar(100),
    entrevista_lugar_n2 varchar(100),
    entrevista_lugar_n3 varchar(100),
    entrevista_lat double precision,
    entrevista_lon double precision,
    hechos_anio_del varchar(20),
    hechos_anio_al varchar(20),
    hechos_lugar_n1 varchar(100),
    hechos_lugar_n2 varchar(100),
    hechos_lugar_n3 varchar(100),
    hechos_lat double precision,
    hechos_lon double precision,
    sector_entrevistado varchar(100),
    transcrita varchar(20),
    etiquetada varchar(20),
    fecha_carga varchar(20),
    fecha_carga_mes varchar(20),
    fecha_carga_anio varchar(20),
    interes_exilio varchar(20) default 'No',
    interes_etnico varchar(20) default 'No',
    aa_paramilitar varchar(20) default 'No',
    aa_guerrilla varchar(20) default 'No',
    aa_fuerza_publica varchar(20) default 'No',
    aa_terceros_civiles varchar(20) default 'No',
    aa_otro_grupo_armado varchar(20) default 'No',
    aa_otro_agente_estado varchar(20) default 'No',
    aa_otro_actor varchar(20) default 'No',
    aa_ns_nr varchar(20) default 'No',
    aa_internacional varchar(20) default 'No',
    viol_homicidio varchar(20) default 'No',
    viol_atentado_vida varchar(20) default 'No',
    viol_amenaza_vida varchar(20) default 'No',
    viol_desaparicion_f varchar(20) default 'No',
    viol_tortura varchar(20) default 'No',
    viol_violencia_sexual varchar(20) default 'No',
    viol_esclavitud varchar(20) default 'No',
    viol_reclutamiento varchar(20) default 'No',
    viol_detencion_arbitraria varchar(20) default 'No',
    viol_secuestro varchar(20) default 'No',
    viol_confinamiento varchar(20) default 'No',
    viol_pillaje varchar(20) default 'No',
    viol_extorsion varchar(20) default 'No',
    viol_ataque_bien_protegido varchar(20) default 'No',
    viol_ataque_indiscriminado varchar(20) default 'No',
    viol_despojo_tierras varchar(20) default 'No',
    viol_desplazamiento_forzado varchar(20) default 'No',
    viol_exilio varchar(20) default 'No',
    i_objetivo_esclarecimiento varchar(20) default 'No',
    i_objetivo_reconocimiento  varchar(20) default 'No',
    i_objetivo_convivencia  varchar(20) default 'No',
    i_objetivo_no_repeticion  varchar(20) default 'No',
    i_enfoque_genero  varchar(20) default 'No',
    i_enfoque_psicosocial varchar(20) default 'No',
    i_enfoque_curso_vida  varchar(20) default 'No',
    i_direccion_investigacion  varchar(20) default 'No',
    i_direccion_territorios varchar(20) default 'No',
    i_direccion_etnica varchar(20) default 'No',
    i_comisionados varchar(20) default 'No',
    i_estrategia_arte varchar(20) default 'No',
    i_estrategia_comunicacion varchar(20) default 'No',
    i_estrategia_participacion varchar(20) default 'No',
    i_estrategia_pedagogia varchar(20) default 'No',
    i_grupo_acceso_informacion varchar(20) default 'No',
    i_presidencia varchar(20) default 'No',
    i_otra varchar(20) default 'No',
    i_enlace varchar(20) default 'No',
    i_sistema_informacion varchar(20) default 'No',
    ia_pueblo_etnico varchar(20) default 'No',
    ia_dialogo_social varchar(20) default 'No',
    ia_genero varchar(20) default 'No',
    ia_enfoque_ps varchar(20) default 'No',
    ia_curso_vida varchar(20) default 'No',
    nucleo_01 varchar(20) default 'No',
    nucleo_02 varchar(20) default 'No',
    nucleo_03 varchar(20) default 'No',
    nucleo_04 varchar(20) default 'No',
    nucleo_05 varchar(20) default 'No',
    nucleo_06 varchar(20) default 'No',
    nucleo_07 varchar(20) default 'No',
    nucleo_08 varchar(20) default 'No',
    nucleo_09 varchar(20) default 'No',
    nucleo_10 varchar(20) default 'No',
    mandato_01 varchar(20) default 'No',
    mandato_02 varchar(20) default 'No',
    mandato_03 varchar(20) default 'No',
    mandato_04 varchar(20) default 'No',
    mandato_05 varchar(20) default 'No',
    mandato_06 varchar(20) default 'No',
    mandato_07 varchar(20) default 'No',
    mandato_08 varchar(20) default 'No',
    mandato_09 varchar(20) default 'No',
    mandato_10 varchar(20) default 'No',
    mandato_11 varchar(20) default 'No',
    mandato_12 varchar(20) default 'No',
    mandato_13 varchar(20) default 'No',
    prioridad_e_fecha varchar(20),
    prioridad_e_ponderacion integer default '-99'::integer,
    prioridad_e_fluidez integer default '-99'::integer,
    prioridad_e_d_hecho integer default '-99'::integer,
    prioridad_e_d_contexto integer default '-99'::integer,
    prioridad_e_d_impacto integer default '-99'::integer,
    prioridad_e_d_justicia integer default '-99'::integer,
    prioridad_e_cierre integer default '-99'::integer,
    prioridad_e_ahora_entiendo text,
    prioridad_e_cambio_perspectiva text,
    prioridad_t_fecha text,
    prioridad_t_ponderacion integer default '-99'::integer,
    prioridad_t_fluidez integer default '-99'::integer,
    prioridad_t_d_hecho integer default '-99'::integer,
    prioridad_t_d_contexto integer default '-99'::integer,
    prioridad_t_d_impacto integer default '-99'::integer,
    prioridad_t_d_justicia varchar(20) default 'N/A',
    prioridad_t_cierre varchar(20) default 'N/A',
    prioridad_t_ahora_entiendo text,
    prioridad_t_cambio_perspectiva text,

    consentimiento_conceder_entrevista varchar(20) default null,
    consentimiento_grabar_audio varchar(20) default null,
    consentimiento_elaborar_informe varchar(20) default null,
    consentimiento_tratamiento_datos_analizar varchar(20) default null,
    consentimiento_tratamiento_datos_analizar_sensible varchar(20) default null,
    consentimiento_tratamiento_datos_utilizar varchar(20) default null,
    consentimiento_tratamiento_datos_utilizar_sensible varchar(20) default null,
    consentimiento_tratamiento_datos_publicar varchar(20) default null,
    fichas_estado_diligenciado varchar(100) default  null,
    fichas_conteo_entrevistado integer default null,
    fichas_conteo_victima integer default null,
    fichas_conteo_responsable integer default null,
    fichas_conteo_hechos integer default null,
    fichas_conteo_violaciones integer default null,
    fichas_conteo_violencia integer default null,
    fichas_conteo_exilio integer default null
);

alter table public.metadatos_nvivo owner to dba;

grant select on public.metadatos_nvivo to solo_lectura;


