drop table if exists  esclarecimiento.excel_co;
create table esclarecimiento.excel_co
(
    id serial not null
        constraint excel_co_pkey
        primary key,
    id_entrevista_colectiva integer,
    codigo_entrevista text,
    medios_virtuales text,
    situacion_actual text,
    personas_entrevistadas integer default 1,
    macroterritorio text,
    territorio text,
    clasificacion integer default 3,
    codigo_entrevistador text,
    grupo_entrevistador text,
    entrevista_fecha_inicio text,
    entrevista_fecha_inicio_mes text,
    entrevista_fecha_final text,
    tiempo_entrevista integer default 0,
    entrevista_lugar_n1 text,
    entrevista_lugar_n2 text,
    entrevista_lugar_n3 text,
    entrevista_lat double precision,
    entrevista_lon double precision,
    sector_entrevistado text,
    tema text,
    objetivo text,
    eventos text,
    tema_anio_del text,
    tema_anio_al text,
    tema_lugar_n1 text,
    tema_lugar_n2 text,
    tema_lugar_n3 text,
    titulo text,
    observaciones text,
    dinamica_1 text,
    dinamica_2 text,
    dinamica_3 text,
    transcrita integer default 0,
    transcrita_fecha text,
    transcrita_fecha_a text,
    transcrita_fecha_m text,
    etiquetada integer default 0,
    etiquetada_fecha text,
    etiquetada_fecha_a text,
    etiquetada_fecha_m text,
    i_objetivo_esclarecimiento integer default 0,
    i_objetivo_reconocimiento integer default 0,
    i_objetivo_convivencia integer default 0,
    i_objetivo_no_repeticion integer default 0,
    i_enfoque_genero integer default 0,
    i_enfoque_psicosocial integer default 0,
    i_enfoque_curso_vida integer default 0,
    i_direccion_investigacion integer default 0,
    i_direccion_territorios integer default 0,
    i_direccion_etnica integer default 0,
    i_comisionados integer default 0,
    i_estrategia_arte integer default 0,
    i_estrategia_comunicacion integer default 0,
    i_estrategia_participacion integer default 0,
    i_estrategia_pedagogia integer default 0,
    i_grupo_acceso_informacion integer default 0,
    i_presidencia integer default 0,
    i_otra integer default 0,
    i_enlace integer default 0,
    i_sistema_informacion integer default 0,
    ia_pueblo_etnico integer default 0,
    ia_dialogo_social integer default 0,
    ia_genero integer default 0,
    ia_enfoque_ps integer default 0,
    ia_curso_vida integer default 0,
    nucleo_01 integer default 0,
    nucleo_02 integer default 0,
    nucleo_03 integer default 0,
    nucleo_04 integer default 0,
    nucleo_05 integer default 0,
    nucleo_06 integer default 0,
    nucleo_07 integer default 0,
    nucleo_08 integer default 0,
    nucleo_09 integer default 0,
    nucleo_10 integer default 0,
    mandato_01 integer default 0,
    mandato_02 integer default 0,
    mandato_03 integer default 0,
    mandato_04 integer default 0,
    mandato_05 integer default 0,
    mandato_06 integer default 0,
    mandato_07 integer default 0,
    mandato_08 integer default 0,
    mandato_09 integer default 0,
    mandato_10 integer default 0,
    mandato_11 integer default 0,
    mandato_12 integer default 0,
    mandato_13 integer default 0,
    a_consentimiento integer default 0,
    a_audio integer default 0,
    a_ficha_corta integer default 0,
    a_ficha_larga integer default 0,
    a_otros integer default 0,
    a_transcripcion_preliminar integer default 0,
    a_transcripcion_final integer default 0,
    a_etiquetado integer default 0,
    a_retroalimentacion integer default 0,
    a_relatoria integer default 0,
    a_certificacion_inicial integer default 0,
    a_certificacion_final integer default 0,
    a_plan_trabajo integer default 0,
    a_valoracion integer default 0,
    fecha_carga text,
    mes_carga text,
    id_entrevistador integer,
    prioridad_e_fecha text,
    prioridad_e_ponderacion integer default '-99'::integer,
    prioridad_e_fluidez integer default '-99'::integer,
    prioridad_e_d_hecho integer default '-99'::integer,
    prioridad_e_d_contexto integer default '-99'::integer,
    prioridad_e_d_impacto integer default '-99'::integer,
    prioridad_e_d_justicia integer default '-99'::integer,
    prioridad_e_cierre integer default '-99'::integer,
    prioridad_e_ahora_entiendo text,
    prioridad_e_cambio_perspectiva text,
    prioridad_t_fecha text,
    prioridad_t_ponderacion integer default '-99'::integer,
    prioridad_t_fluidez integer default '-99'::integer,
    prioridad_t_d_hecho integer default '-99'::integer,
    prioridad_t_d_contexto integer default '-99'::integer,
    prioridad_t_d_impacto integer default '-99'::integer,
    prioridad_t_d_justicia integer default '-99'::integer,
    prioridad_t_cierre integer default '-99'::integer,
    prioridad_t_ahora_entiendo text,
    prioridad_t_cambio_perspectiva text,
    minutos_entrevista integer default '-99'::integer,
    minutos_transcripcion integer default '-99'::integer,
    minutos_etiquetado integer default '-99'::integer,
    minutos_diligenciado integer default '-99'::integer
);

comment on column esclarecimiento.excel_co.id_entrevista_colectiva is 'Trazabilidad a tabla original';


alter table esclarecimiento.excel_co owner to dba;

grant select on esclarecimiento.excel_co to solo_lectura;

create index excel_co_id_entrevistador_index
    on esclarecimiento.excel_co (id_entrevistador);

create unique index excel_co_codigo_entrevista_uindex
    on esclarecimiento.excel_co (codigo_entrevista);
create index excel_co_id_entrevista_colectiva_index
    on esclarecimiento.excel_co (id_entrevista_colectiva);

