drop table if exists esclarecimiento.excel_entrevista_integrado cascade ;
create table esclarecimiento.excel_entrevista_integrado
(
    id serial not null
        constraint excel_entrevista_integrado_pkey
            primary key,
    codigo_entrevista text,
    personas_entrevistadas integer default 1,
    es_virtual integer default 0,
    situacion_actual text default 'Finalizada'::text,
    clasificacion integer default 3,
    macroterritorio text,
    territorio text,
    codigo_entrevistador text,
    grupo_entrevistador text,
    entrevista_fecha text,
    entrevista_mes text,
    tiempo_entrevista integer default 0,
    entrevista_lugar_n1 text,
    entrevista_lugar_n2 text,
    entrevista_lugar_n3 text,
    hechos_anio_del text,
    hechos_anio_al text,
    sector_entrevistado text,
    conteo_consultas integer,
    interes_exilio integer default 0,
    tipo_entrevista text,
    titulo text,
    dinamica_1 text,
    dinamica_2 text,
    dinamica_3 text,
    transcrita integer default 0,
    conteo_caracteres bigint default 0,
    transcrita_fecha text,
    transcrita_fecha_a text,
    transcrita_fecha_m text,
    etiquetada integer default 0,
    conteo_etiquetas integer default 0,
    etiquetada_fecha text,
    etiquetada_fecha_a text,
    etiquetada_fecha_m text,
    i_objetivo_esclarecimiento integer default 0,
    i_objetivo_reconocimiento integer default 0,
    i_objetivo_convivencia integer default 0,
    i_objetivo_no_repeticion integer default 0,
    i_enfoque_genero integer default 0,
    i_enfoque_psicosocial integer default 0,
    i_enfoque_curso_vida integer default 0,
    i_direccion_investigacion integer default 0,
    i_direccion_territorios integer default 0,
    i_direccion_etnica integer default 0,
    i_comisionados integer default 0,
    i_estrategia_arte integer default 0,
    i_estrategia_comunicacion integer default 0,
    i_estrategia_participacion integer default 0,
    i_estrategia_pedagogia integer default 0,
    i_grupo_acceso_informacion integer default 0,
    i_presidencia integer default 0,
    i_otra integer default 0,
    i_enlace integer default 0,
    i_sistema_informacion integer default 0,
    ia_pueblo_etnico integer default 0,
    ia_dialogo_social integer default 0,
    ia_genero integer default 0,
    ia_enfoque_ps integer default 0,
    ia_curso_vida integer default 0,
    nucleo_01 integer default 0,
    nucleo_02 integer default 0,
    nucleo_03 integer default 0,
    nucleo_04 integer default 0,
    nucleo_05 integer default 0,
    nucleo_06 integer default 0,
    nucleo_07 integer default 0,
    nucleo_08 integer default 0,
    nucleo_09 integer default 0,
    nucleo_10 integer default 0,
    mandato_01 integer default 0,
    mandato_02 integer default 0,
    mandato_03 integer default 0,
    mandato_04 integer default 0,
    mandato_05 integer default 0,
    mandato_06 integer default 0,
    mandato_07 integer default 0,
    mandato_08 integer default 0,
    mandato_09 integer default 0,
    mandato_10 integer default 0,
    mandato_11 integer default 0,
    mandato_12 integer default 0,
    mandato_13 integer default 0,
    a_consentimiento integer default 0,
    a_audio integer default 0,
    a_ficha_corta integer default 0,
    a_ficha_larga integer default 0,
    a_otros integer default 0,
    a_transcripcion_preliminar integer default 0,
    a_transcripcion_final integer default 0,
    a_etiquetado integer default 0,
    a_retroalimentacion integer default 0,
    a_relatoria integer default 0,
    a_certificacion_inicial integer default 0,
    a_certificacion_final integer default 0,
    a_plan_trabajo integer default 0,
    a_valoracion integer default 0,
    entrevista_lat double precision,
    entrevista_lon double precision,
    prioridad_e_fecha text,
    prioridad_e_ponderacion integer default '-99'::integer,
    prioridad_e_fluidez integer default '-99'::integer,
    prioridad_e_d_hecho integer default '-99'::integer,
    prioridad_e_d_contexto integer default '-99'::integer,
    prioridad_e_d_impacto integer default '-99'::integer,
    prioridad_e_d_justicia integer default '-99'::integer,
    prioridad_e_cierre integer default '-99'::integer,
    prioridad_e_ahora_entiendo text,
    prioridad_e_cambio_perspectiva text,
    prioridad_t_fecha text,
    prioridad_t_ponderacion integer default '-99'::integer,
    prioridad_t_fluidez integer default '-99'::integer,
    prioridad_t_d_hecho integer default '-99'::integer,
    prioridad_t_d_contexto integer default '-99'::integer,
    prioridad_t_d_impacto integer default '-99'::integer,
    prioridad_t_d_justicia integer default '-99'::integer,
    prioridad_t_cierre integer default '-99'::integer,
    prioridad_t_ahora_entiendo text,
    prioridad_t_cambio_perspectiva text,
    procesamiento_requisitos_minimos integer default 0,
    procesamiento_transcrito integer default '-99'::integer,
    procesamiento_etiquetado integer default '-99'::integer,
    procesamiento_cerrado integer default '-99'::integer,
    consentimiento_conceder_entrevista integer default '-99'::integer,
    consentimiento_grabar_audio integer default '-99'::integer,
    consentimiento_elaborar_informe integer default '-99'::integer,
    consentimiento_tratamiento_datos_analizar integer default '-99'::integer,
    consentimiento_tratamiento_datos_analizar_sensible integer default '-99'::integer,
    consentimiento_tratamiento_datos_utilizar integer default '-99'::integer,
    consentimiento_tratamiento_datos_utilizar_sensible integer default '-99'::integer,
    consentimiento_tratamiento_datos_publicar integer default '-99'::integer,
    fichas_estado_diligenciado text,
    fichas_conteo_entrevistado integer default '-99'::integer,
    fichas_conteo_victima integer default '-99'::integer,
    fichas_conteo_responsable integer default '-99'::integer,
    fichas_conteo_hechos integer default '-99'::integer,
    fichas_conteo_violaciones integer default '-99'::integer,
    fichas_conteo_violencia integer default '-99'::integer,
    fichas_conteo_exilio integer default '-99'::integer,
    fichas_conteo_alertas integer default '-99'::integer,
    minutos_entrevista integer default '-99'::integer,
    minutos_transcripcion integer default '-99'::integer,
    minutos_etiquetado integer default '-99'::integer,
    minutos_diligenciado integer default '-99'::integer,
    fecha_carga text,
    mes_carga text,
    id_entrevistador integer
);

alter table esclarecimiento.excel_entrevista_integrado owner to dba;

create index excel_entrevista_integrado_codigo_entrevista_index
    on esclarecimiento.excel_entrevista_integrado (codigo_entrevista);

create index excel_entrevista_integrado_id_entrevistador_index
    on esclarecimiento.excel_entrevista_integrado (id_entrevistador);

