drop table if exists esclarecimiento.excel_entrevista_pr cascade ;
create table esclarecimiento.excel_entrevista_pr
(
    id_entrevista_profundidad integer not null
        constraint excel_entrevista_pr_pkey
            primary key,
    correlativo integer,
    clasificacion integer default 3,
    tipo_entrevista text,
    codigo_entrevista text,
    codigo_entrevistador text,
    macroterritorio_id integer,
    macroterritorio_txt text,
    territorio_id integer,
    territorio_txt text,
    grupo_id integer,
    grupo_txt text,
    entrevista_fecha_inicio text,
    entrevista_fecha_final text,
    entrevista_avance_codigo text,
    entrevista_avance_txt text,
    tiempo_entrevista text,
    entrevista_lugar_n1_codigo text,
    entrevista_lugar_n1_txt text,
    entrevista_lugar_n2_codigo text,
    entrevista_lugar_n2_txt text,
    entrevista_lugar_n3_codigo text,
    entrevista_lugar_n3_txt text,
    titulo text,
    objetivo text,
    tema_1 text,
    tema_2 text,
    tema_3 text,
    tema_4 text,
    tema_5 text,
    dinamica_1 text,
    dinamica_2 text,
    dinamica_3 text,
    entrevistado_nombres text,
    entrevistado_apellidos text,
    sector_entrevistado text,
    anotaciones text,
    remitido text,
    policia_parte integer,
    policia_rango text,
    paramilitar_parte integer,
    paramilitar_rango text,
    guerrilla_parte integer,
    guerrilla_rango text,
    ejercito_parte integer,
    ejercito_rango text,
    fuerza_aerea_parte integer,
    fuerza_aerea_rango text,
    fuerza_naval_parte integer,
    fuerza_naval_rango text,
    tercero_civil_parte integer,
    tercero_civil_cual text,
    agente_estado_parte integer,
    agente_estado_cual text,
    transcrita text,
    etiquetada text,
    i_objetivo_esclarecimiento integer default 0,
    i_objetivo_reconocimiento integer default 0,
    i_objetivo_convivencia integer default 0,
    i_objetivo_no_repeticion integer default 0,
    i_enfoque_genero integer default 0,
    i_enfoque_psicosocial integer default 0,
    i_enfoque_curso_vida integer default 0,
    i_direccion_investigacion integer default 0,
    i_direccion_territorios integer default 0,
    i_direccion_etnica integer default 0,
    i_comisionados integer default 0,
    i_estrategia_arte integer default 0,
    i_estrategia_comunicacion integer default 0,
    i_estrategia_participacion integer default 0,
    i_estrategia_pedagogia integer default 0,
    i_grupo_acceso_informacion integer default 0,
    i_presidencia integer default 0,
    i_otra integer default 0,
    i_enlace integer default 0,
    i_sistema_informacion integer default 0,
    ia_pueblo_etnico integer default 0,
    ia_dialogo_social integer default 0,
    ia_ds_o_convivencia integer default 0,
    ia_ds_o_reconocimiento integer default 0,
    ia_ds_o_no_repeticion integer default 0,
    ia_genero integer default 0,
    ia_enfoque_ps integer default 0,
    ia_curso_vida integer default 0,
    nucleo_01 integer default 0,
    nucleo_02 integer default 0,
    nucleo_03 integer default 0,
    nucleo_04 integer default 0,
    nucleo_05 integer default 0,
    nucleo_06 integer default 0,
    nucleo_07 integer default 0,
    nucleo_08 integer default 0,
    nucleo_09 integer default 0,
    nucleo_10 integer default 0,
    mandato_01 integer default 0,
    mandato_02 integer default 0,
    mandato_03 integer default 0,
    mandato_04 integer default 0,
    mandato_05 integer default 0,
    mandato_06 integer default 0,
    mandato_07 integer default 0,
    mandato_08 integer default 0,
    mandato_09 integer default 0,
    mandato_10 integer default 0,
    mandato_11 integer default 0,
    mandato_12 integer default 0,
    mandato_13 integer default 0,
    prioridad_e_fecha text,
    prioridad_e_ponderacion integer default '-99'::integer,
    prioridad_e_fluidez integer default '-99'::integer,
    prioridad_e_d_hecho integer default '-99'::integer,
    prioridad_e_d_contexto integer default '-99'::integer,
    prioridad_e_d_impacto integer default '-99'::integer,
    prioridad_e_d_justicia integer default '-99'::integer,
    prioridad_e_cierre integer default '-99'::integer,
    prioridad_e_ahora_entiendo text,
    prioridad_e_cambio_perspectiva text,
    prioridad_t_fecha text,
    prioridad_t_ponderacion integer default '-99'::integer,
    prioridad_t_fluidez integer default '-99'::integer,
    prioridad_t_d_hecho integer default '-99'::integer,
    prioridad_t_d_contexto integer default '-99'::integer,
    prioridad_t_d_impacto integer default '-99'::integer,
    prioridad_t_d_justicia integer default '-99'::integer,
    prioridad_t_cierre integer default '-99'::integer,
    prioridad_t_ahora_entiendo text,
    prioridad_t_cambio_perspectiva text,
    a_consentimiento integer default 0,
    a_audio integer default 0,
    a_ficha_corta integer default 0,
    a_ficha_larga integer default 0,
    a_otros integer default 0,
    a_transcripcion_preliminar integer default 0,
    a_transcripcion_final integer default 0,
    a_retroalimentacion integer default 0,
    a_relatoria integer default 0,
    a_certificacion_inicial integer default 0,
    a_certificacion_final integer default 0,
    a_plan_trabajo integer default 0,
    a_valoracion integer default 0,
    entrevista_lat double precision,
    entrevista_lon double precision,
    transcripcion_html text,
    etiquetado_json text,
    created_at timestamp(0) not null,
    updated_at timestamp(0),
    id_entrevistador integer
);

alter table esclarecimiento.excel_entrevista_pr owner to dba;

grant select on esclarecimiento.excel_entrevista_pr to solo_lectura;

create index excel_entrevista_pr_entrevista_index
    on esclarecimiento.excel_entrevista_pr (codigo_entrevista);

create index excel_entrevista_pr_id_entrevistador_index
    on esclarecimiento.excel_entrevista_pr (id_entrevistador);

