-- LISTADO DE PAISES segun ISO 3166
drop table if exists catalogos.iso_pais;
create table catalogos.iso_pais
(
    id_iso_pais serial
        constraint iso_pais_pk
            primary key,
    descripcion varchar(200),
    iso2 varchar(10),
    iso3 varchar(3),
    numero integer
);

comment on table catalogos.iso_pais is 'Codigos de paises de acuerdo al ISO 3166-1';

comment on column catalogos.iso_pais.descripcion is 'Nombre del país';

comment on column catalogos.iso_pais.iso2 is 'Codigo de 2 letras';

comment on column catalogos.iso_pais.iso3 is 'Código de 3 letras';

alter table catalogos.iso_pais owner to dba;

create index iso_pais_descripcion_index
    on catalogos.iso_pais (descripcion);


-- DATOS
-- delete from catalogos.iso_pais;
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Afghanistan','AF','AFG',4);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Albania','AL','ALB',8);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Algeria','DZ','DZA',12);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('American Samoa','AS','ASM',16);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Andorra','AD','AND',20);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Angola','AO','AGO',24);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Anguilla','AI','AIA',660);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Antarctica','AQ','ATA',10);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Antigua and Barbuda','AG','ATG',28);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Argentina','AR','ARG',32);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Armenia','AM','ARM',51);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Aruba','AW','ABW',533);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Australia','AU','AUS',36);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Austria','AT','AUT',40);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Azerbaijan','AZ','AZE',31);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bahamas (the)','BS','BHS',44);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bahrain','BH','BHR',48);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bangladesh','BD','BGD',50);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Barbados','BB','BRB',52);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Belarus','BY','BLR',112);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Belgium','BE','BEL',56);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Belize','BZ','BLZ',84);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Benin','BJ','BEN',204);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bermuda','BM','BMU',60);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bhutan','BT','BTN',64);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bolivia (Plurinational State of)','BO','BOL',68);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bonaire, Sint Eustatius and Saba','BQ','BES',535);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bosnia and Herzegovina','BA','BIH',70);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Botswana','BW','BWA',72);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bouvet Island','BV','BVT',74);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Brazil','BR','BRA',76);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('British Indian Ocean Territory (the)','IO','IOT',86);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Brunei Darussalam','BN','BRN',96);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bulgaria','BG','BGR',100);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Burkina Faso','BF','BFA',854);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Burundi','BI','BDI',108);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Cabo Verde','CV','CPV',132);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Cambodia','KH','KHM',116);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Cameroon','CM','CMR',120);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Canada','CA','CAN',124);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Cayman Islands (the)','KY','CYM',136);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Central African Republic (the)','CF','CAF',140);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Chad','TD','TCD',148);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Chile','CL','CHL',152);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('China','CN','CHN',156);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Christmas Island','CX','CXR',162);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Cocos (Keeling) Islands (the)','CC','CCK',166);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Colombia','CO','COL',170);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Comoros (the)','KM','COM',174);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Congo (the Democratic Republic of the)','CD','COD',180);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Congo (the)','CG','COG',178);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Cook Islands (the)','CK','COK',184);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Costa Rica','CR','CRI',188);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Croatia','HR','HRV',191);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Cuba','CU','CUB',192);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Curaçao','CW','CUW',531);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Cyprus','CY','CYP',196);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Czechia','CZ','CZE',203);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Côte d''Ivoire','CI','CIV',384);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Denmark','DK','DNK',208);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Djibouti','DJ','DJI',262);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Dominica','DM','DMA',212);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Dominican Republic (the)','DO','DOM',214);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Ecuador','EC','ECU',218);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Egypt','EG','EGY',818);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('El Salvador','SV','SLV',222);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Equatorial Guinea','GQ','GNQ',226);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Eritrea','ER','ERI',232);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Estonia','EE','EST',233);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Eswatini','SZ','SWZ',748);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Ethiopia','ET','ETH',231);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Falkland Islands (the) [Malvinas]','FK','FLK',238);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Faroe Islands (the)','FO','FRO',234);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Fiji','FJ','FJI',242);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Finland','FI','FIN',246);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('France','FR','FRA',250);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('French Guiana','GF','GUF',254);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('French Polynesia','PF','PYF',258);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('French Southern Territories (the)','TF','ATF',260);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Gabon','GA','GAB',266);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Gambia (the)','GM','GMB',270);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Georgia','GE','GEO',268);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Germany','DE','DEU',276);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Ghana','GH','GHA',288);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Gibraltar','GI','GIB',292);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Greece','GR','GRC',300);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Greenland','GL','GRL',304);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Grenada','GD','GRD',308);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guadeloupe','GP','GLP',312);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guam','GU','GUM',316);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guatemala','GT','GTM',320);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guernsey','GG','GGY',831);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guinea','GN','GIN',324);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guinea-Bissau','GW','GNB',624);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guyana','GY','GUY',328);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Haiti','HT','HTI',332);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Heard Island and McDonald Islands','HM','HMD',334);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Holy See (the)','VA','VAT',336);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Honduras','HN','HND',340);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Hong Kong','HK','HKG',344);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Hungary','HU','HUN',348);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Iceland','IS','ISL',352);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('India','IN','IND',356);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Indonesia','ID','IDN',360);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Iran (Islamic Republic of)','IR','IRN',364);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Iraq','IQ','IRQ',368);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Ireland','IE','IRL',372);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Isle of Man','IM','IMN',833);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Israel','IL','ISR',376);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Italy','IT','ITA',380);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Jamaica','JM','JAM',388);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Japan','JP','JPN',392);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Jersey','JE','JEY',832);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Jordan','JO','JOR',400);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Kazakhstan','KZ','KAZ',398);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Kenya','KE','KEN',404);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Kiribati','KI','KIR',296);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Korea (the Democratic People''s Republic of)','KP','PRK',408);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Korea (the Republic of)','KR','KOR',410);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Kuwait','KW','KWT',414);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Kyrgyzstan','KG','KGZ',417);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Lao People''s Democratic Republic (the)','LA','LAO',418);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Latvia','LV','LVA',428);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Lebanon','LB','LBN',422);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Lesotho','LS','LSO',426);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Liberia','LR','LBR',430);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Libya','LY','LBY',434);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Liechtenstein','LI','LIE',438);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Lithuania','LT','LTU',440);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Luxembourg','LU','LUX',442);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Macao','MO','MAC',446);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Madagascar','MG','MDG',450);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Malawi','MW','MWI',454);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Malaysia','MY','MYS',458);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Maldives','MV','MDV',462);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mali','ML','MLI',466);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Malta','MT','MLT',470);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Marshall Islands (the)','MH','MHL',584);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Martinique','MQ','MTQ',474);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mauritania','MR','MRT',478);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mauritius','MU','MUS',480);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mayotte','YT','MYT',175);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mexico','MX','MEX',484);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Micronesia (Federated States of)','FM','FSM',583);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Moldova (the Republic of)','MD','MDA',498);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Monaco','MC','MCO',492);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mongolia','MN','MNG',496);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Montenegro','ME','MNE',499);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Montserrat','MS','MSR',500);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Morocco','MA','MAR',504);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mozambique','MZ','MOZ',508);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Myanmar','MM','MMR',104);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Namibia','NA','NAM',516);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Nauru','NR','NRU',520);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Nepal','NP','NPL',524);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Netherlands (the)','NL','NLD',528);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('New Caledonia','NC','NCL',540);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('New Zealand','NZ','NZL',554);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Nicaragua','NI','NIC',558);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Niger (the)','NE','NER',562);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Nigeria','NG','NGA',566);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Niue','NU','NIU',570);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Norfolk Island','NF','NFK',574);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Northern Mariana Islands (the)','MP','MNP',580);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Norway','NO','NOR',578);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Oman','OM','OMN',512);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Pakistan','PK','PAK',586);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Palau','PW','PLW',585);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Palestine, State of','PS','PSE',275);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Panama','PA','PAN',591);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Papua New Guinea','PG','PNG',598);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Paraguay','PY','PRY',600);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Peru','PE','PER',604);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Philippines (the)','PH','PHL',608);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Pitcairn','PN','PCN',612);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Poland','PL','POL',616);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Portugal','PT','PRT',620);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Puerto Rico','PR','PRI',630);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Qatar','QA','QAT',634);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Republic of North Macedonia','MK','MKD',807);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Romania','RO','ROU',642);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Russian Federation (the)','RU','RUS',643);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Rwanda','RW','RWA',646);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Réunion','RE','REU',638);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Saint Barthélemy','BL','BLM',652);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Saint Helena, Ascension and Tristan da Cunha','SH','SHN',654);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Saint Kitts and Nevis','KN','KNA',659);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Saint Lucia','LC','LCA',662);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Saint Martin (French part)','MF','MAF',663);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Saint Pierre and Miquelon','PM','SPM',666);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Saint Vincent and the Grenadines','VC','VCT',670);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Samoa','WS','WSM',882);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('San Marino','SM','SMR',674);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Sao Tome and Principe','ST','STP',678);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Saudi Arabia','SA','SAU',682);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Senegal','SN','SEN',686);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Serbia','RS','SRB',688);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Seychelles','SC','SYC',690);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Sierra Leone','SL','SLE',694);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Singapore','SG','SGP',702);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Sint Maarten (Dutch part)','SX','SXM',534);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Slovakia','SK','SVK',703);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Slovenia','SI','SVN',705);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Solomon Islands','SB','SLB',90);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Somalia','SO','SOM',706);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('South Africa','ZA','ZAF',710);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('South Georgia and the South Sandwich Islands','GS','SGS',239);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('South Sudan','SS','SSD',728);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Spain','ES','ESP',724);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Sri Lanka','LK','LKA',144);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Sudan (the)','SD','SDN',729);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Suriname','SR','SUR',740);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Svalbard and Jan Mayen','SJ','SJM',744);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Sweden','SE','SWE',752);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Switzerland','CH','CHE',756);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Syrian Arab Republic','SY','SYR',760);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Taiwan (Province of China)','TW','TWN',158);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Tajikistan','TJ','TJK',762);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Tanzania, United Republic of','TZ','TZA',834);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Thailand','TH','THA',764);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Timor-Leste','TL','TLS',626);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Togo','TG','TGO',768);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Tokelau','TK','TKL',772);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Tonga','TO','TON',776);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Trinidad and Tobago','TT','TTO',780);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Tunisia','TN','TUN',788);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Turkey','TR','TUR',792);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Turkmenistan','TM','TKM',795);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Turks and Caicos Islands (the)','TC','TCA',796);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Tuvalu','TV','TUV',798);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Uganda','UG','UGA',800);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Ukraine','UA','UKR',804);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('United Arab Emirates (the)','AE','ARE',784);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('United Kingdom of Great Britain and Northern Ireland (the)','GB','GBR',826);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('United States Minor Outlying Islands (the)','UM','UMI',581);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('United States of America (the)','US','USA',840);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Uruguay','UY','URY',858);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Uzbekistan','UZ','UZB',860);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Vanuatu','VU','VUT',548);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Venezuela (Bolivarian Republic of)','VE','VEN',862);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Viet Nam','VN','VNM',704);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Virgin Islands (British)','VG','VGB',92);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Virgin Islands (U.S.)','VI','VIR',850);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Wallis and Futuna','WF','WLF',876);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Western Sahara','EH','ESH',732);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Yemen','YE','YEM',887);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Zambia','ZM','ZMB',894);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Zimbabwe','ZW','ZWE',716);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Åland Islands','AX','ALA',248);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Andorra','AD','AND',20);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Emiratos Árabes Unidos','AE','ARE',784);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Afganistán','AF','AFG',4);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Antigua y Barbuda','AG','ATG',28);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Anguila','AI','AIA',660);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Albania','AL','ALB',8);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Armenia','AM','ARM',51);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Antillas Neerlandesas','AN','ANT',530);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Angola','AO','AGO',24);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Antártida','AQ','ATA',10);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Argentina','AR','ARG',32);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Samoa Americana','AS','ASM',16);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Austria','AT','AUT',40);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Australia','AU','AUS',36);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Aruba','AW','ABW',533);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Áland','AX','ALA',248);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Azerbaiyán','AZ','AZE',31);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bosnia y Herzegovina','BA','BIH',70);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Barbados','BB','BRB',52);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bangladesh','BD','BGD',50);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bélgica','BE','BEL',56);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Burkina Faso','BF','BFA',854);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bulgaria','BG','BGR',100);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bahréin','BH','BHR',48);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Burundi','BI','BDI',108);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Benin','BJ','BEN',204);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('San Bartolomé','BL','BLM',652);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bermudas','BM','BMU',60);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Brunéi','BN','BRN',96);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bolivia','BO','BOL',68);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Brasil','BR','BRA',76);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bahamas','BS','BHS',44);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Bhután','BT','BTN',64);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Isla Bouvet','BV','BVT',74);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Botsuana','BW','BWA',72);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Belarús','BY','BLR',112);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Belice','BZ','BLZ',84);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Canadá','CA','CAN',124);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Cocos','CC','CCK',166);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('República Centro-Africana','CF','CAF',140);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Congo','CG','COG',178);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Suiza','CH','CHE',756);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Costa de Marfil','CI','CIV',384);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Cook','CK','COK',184);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Chile','CL','CHL',152);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Camerún','CM','CMR',120);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('China','CN','CHN',156);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Colombia','CO','COL',170);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Costa Rica','CR','CRI',188);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Cuba','CU','CUB',192);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Cabo Verde','CV','CPV',132);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Christmas','CX','CXR',162);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Chipre','CY','CYP',196);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('República Checa','CZ','CZE',203);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Alemania','DE','DEU',276);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Yibuti','DJ','DJI',262);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Dinamarca','DK','DNK',208);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Domínica','DM','DMA',212);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('República Dominicana','DO','DOM',214);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Argel','DZ','DZA',12);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Ecuador','EC','ECU',218);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Estonia','EE','EST',233);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Egipto','EG','EGY',818);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Sahara Occidental','EH','ESH',732);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Eritrea','ER','ERI',232);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('España','ES','ESP',724);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Etiopía','ET','ETH',231);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Finlandia','FI','FIN',246);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Fiji','FJ','FJI',242);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Malvinas','FK','KLK',238);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Micronesia','FM','FSM',583);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Faroe','FO','FRO',234);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Francia','FR','FRA',250);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Gabón','GA','GAB',266);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Reino Unido','GB','GBR',826);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Granada','GD','GRD',308);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Georgia','GE','GEO',268);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guayana Francesa','GF','GUF',254);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guernsey','GG','GGY',831);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Ghana','GH','GHA',288);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Gibraltar','GI','GIB',292);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Groenlandia','GL','GRL',304);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Gambia','GM','GMB',270);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guinea','GN','GIN',324);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guadalupe','GP','GLP',312);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guinea Ecuatorial','GQ','GNQ',226);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Grecia','GR','GRC',300);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Georgia del Sur e Islas Sandwich del Sur','GS','SGS',239);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guatemala','GT','GTM',320);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guam','GU','GUM',316);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guinea-Bissau','GW','GNB',624);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Guayana','GY','GUY',328);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Hong Kong','HK','HKG',344);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Heard y McDonald','HM','HMD',334);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Honduras','HN','HND',340);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Croacia','HR','HRV',191);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Haití','HT','HTI',332);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Hungría','HU','HUN',348);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Indonesia','ID','IDN',360);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Irlanda','IE','IRL',372);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Israel','IL','ISR',376);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Isla de Man','IM','IMN',833);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('India','IN','IND',356);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Territorio Británico del Océano Índico','IO','IOT',86);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Irak','IQ','IRQ',368);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Irán','IR','IRN',364);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islandia','IS','ISL',352);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Italia','IT','ITA',380);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Jersey','JE','JEY',832);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Jamaica','JM','JAM',388);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Jordania','JO','JOR',400);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Japón','JP','JPN',392);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Kenia','KE','KEN',404);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Kirguistán','KG','KGZ',417);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Camboya','KH','KHM',116);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Kiribati','KI','KIR',296);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Comoros','KM','COM',174);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('San Cristóbal y Nieves','KN','KNA',659);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Corea del Norte','KP','PRK',408);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Corea del Sur','KR','KOR',410);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Kuwait','KW','KWT',414);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Caimán','KY','CYM',136);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Kazajstán','KZ','KAZ',398);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Laos','LA','LAO',418);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Líbano','LB','LBN',422);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Santa Lucía','LC','LCA',662);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Liechtenstein','LI','LIE',438);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Sri Lanka','LK','LKA',144);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Liberia','LR','LBR',430);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Lesotho','LS','LSO',426);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Lituania','LT','LTU',440);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Luxemburgo','LU','LUX',442);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Letonia','LV','LVA',428);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Libia','LY','LBY',434);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Marruecos','MA','MAR',504);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mónaco','MC','MCO',492);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Moldova','MD','MDA',498);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Montenegro','ME','MNE',499);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Madagascar','MG','MDG',450);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Marshall','MH','MHL',584);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Macedonia','MK','MKD',807);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mali','ML','MLI',466);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Myanmar','MM','MMR',104);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mongolia','MN','MNG',496);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Macao','MO','MAC',446);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Martinica','MQ','MTQ',474);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mauritania','MR','MRT',478);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Montserrat','MS','MSR',500);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Malta','MT','MLT',470);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mauricio','MU','MUS',480);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Maldivas','MV','MDV',462);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Malawi','MW','MWI',454);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('México','MX','MEX',484);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Malasia','MY','MYS',458);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mozambique','MZ','MOZ',508);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Namibia','NA','NAM',516);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Nueva Caledonia','NC','NCL',540);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Níger','NE','NER',562);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Norkfolk','NF','NFK',574);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Nigeria','NG','NGA',566);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Nicaragua','NI','NIC',558);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Países Bajos','NL','NLD',528);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Noruega','NO','NOR',578);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Nepal','NP','NPL',524);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Nauru','NR','NRU',520);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Niue','NU','NIU',570);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Nueva Zelanda','NZ','NZL',554);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Omán','OM','OMN',512);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Panamá','PA','PAN',591);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Perú','PE','PER',604);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Polinesia Francesa','PF','PYF',258);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Papúa Nueva Guinea','PG','PNG',598);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Filipinas','PH','PHL',608);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Pakistán','PK','PAK',586);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Polonia','PL','POL',616);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('San Pedro y Miquelón','PM','SPM',666);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Pitcairn','PN','PCN',612);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Puerto Rico','PR','PRI',630);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Palestina','PS','PSE',275);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Portugal','PT','PRT',620);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Palaos','PW','PLW',585);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Paraguay','PY','PRY',600);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Qatar','QA','QAT',634);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Reunión','RE','REU',638);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Rumanía','RO','ROU',642);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Serbia y Montenegro','RS','SRB',688);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Rusia','RU','RUS',643);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Ruanda','RW','RWA',646);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Arabia Saudita','SA','SAU',682);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Solomón','SB','SLB',90);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Seychelles','SC','SYC',690);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Sudán','SD','SDN',736);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Suecia','SE','SWE',752);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Singapur','SG','SGP',702);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Santa Elena','SH','SHN',654);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Eslovenia','SI','SVN',705);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Svalbard y Jan Mayen','SJ','SJM',744);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Eslovaquia','SK','SVK',703);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Sierra Leona','SL','SLE',694);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('San Marino','SM','SMR',674);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Senegal','SN','SEN',686);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Somalia','SO','SOM',706);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Surinam','SR','SUR',740);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Santo Tomé y Príncipe','ST','STP',678);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('El Salvador','SV','SLV',222);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Siria','SY','SYR',760);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Suazilandia','SZ','SWZ',748);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Turcas y Caicos','TC','TCA',796);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Chad','TD','TCD',148);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Territorios Australes Franceses','TF','ATF',260);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Togo','TG','TGO',768);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Tailandia','TH','THA',764);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Tanzania','TH','TZA',834);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Tayikistán','TJ','TJK',762);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Tokelau','TK','TKL',772);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Timor-Leste','TL','TLS',626);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Turkmenistán','TM','TKM',795);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Túnez','TN','TUN',788);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Tonga','TO','TON',776);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Turquía','TR','TUR',792);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Trinidad y Tobago','TT','TTO',780);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Tuvalu','TV','TUV',798);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Taiwán','TW','TWN',158);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Ucrania','UA','UKR',804);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Uganda','UG','UGA',800);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Estados Unidos de América','US','USA',840);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Uruguay','UY','URY',858);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Uzbekistán','UZ','UZB',860);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Ciudad del Vaticano','VA','VAT',336);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('San Vicente y las Granadinas','VC','VCT',670);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Venezuela','VE','VEN',862);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Vírgenes Británicas','VG','VGB',92);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Islas Vírgenes de los Estados Unidos de América','VI','VIR',850);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Vietnam','VN','VNM',704);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Vanuatu','VU','VUT',548);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Wallis y Futuna','WF','WLF',876);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Samoa','WS','WSM',882);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Yemen','YE','YEM',887);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Mayotte','YT','MYT',175);
insert into catalogos.iso_pais (descripcion,iso2,iso3,numero) values('Sudáfrica','ZA','ZAF',710);