update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Coalición contra la Vinculación de Niños, Niñas y Jóvenes al Conflicto Armado en Colombia - COALICO' where codigo='119-CI-00040';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00224';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Colectivo de Abogados José Alvear Restrepo - CAJAR' where codigo='252-CI-00231';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Coordinación Colombia Europa Estados Unidos - CCEEU' where codigo='119-CI-00232';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Corporación Jurídica Yira Castro - CJYC' where codigo='119-CI-00238';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5541, remitente_nombre='Federación Colombiana de Trabajadores de la Educación - FECODE' where codigo='353-CI-00253';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='058-CI-00254';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Asociación Campaña Colombiana Contra Minas - CCCM' where codigo='119-CI-00259';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5536, remitente_nombre='Movimiento Nacional de Víctimas de Crímenes de Estado - MOVICE' where codigo='119-CI-00266';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00307';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00308';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5538, remitente_nombre='Consejo Comunitario de la Cuenca del Río Cauca y Microcuenca Teta Mazamorrero|Consejo Comunitario Cuenca Río Timba Marilópez' where codigo='119-CI-00309';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5538, remitente_nombre='Consejo Comunitario de la Cuenca del Río Cauca y Microcuenca Teta Mazamorrero|Consejo Comunitario Cuenca Río Timba Marilópez' where codigo='119-CI-00310';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00311';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Corporación Jurídica Yira Castro - CJYC' where codigo='119-CI-00313';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Colectivo de Abogados José Alvear Restrepo - CAJAR|Colectivo Sociojurídico Orlando Fals Borda|Comisión Intereclesial de Justicia y Paz' where codigo='119-CI-00319';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Corporación Jurídica Libertad' where codigo='119-CI-00323';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5535, remitente_nombre='Corporación Sisma Mujer|Red Nacional de Mujeres Defensoras' where codigo='119-CI-00328';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5535, remitente_nombre='Corporación Sisma Mujer|Red Nacional de Mujeres Defensoras' where codigo='119-CI-00379';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00388';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5536, remitente_nombre='Movimiento Nacional de Víctimas de Crímenes de Estado - MOVICE' where codigo='262-CI-00390';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='748-CI-00513';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='748-CI-00514';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='748-CI-00515';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Corporación Mil Víctimas' where codigo='748-CI-00542';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Fundación Comité de Solidaridad con los Presos Políticos - CSPP' where codigo='748-CI-00562';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Instituto de Estudios para el Desarrollo y la Paz - INDEPAZ' where codigo='748-CI-00589';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Corporación Solidaridad Jurídica' where codigo='748-CI-00597';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Fundación Comité de Solidaridad con los Presos Políticos - CSPP' where codigo='748-CI-00608';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Corporación Humanas' where codigo='262-CI-00610';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Corporación Regional Para la Defensa de los Derechos Humanos - CREDHOS' where codigo='748-CI-00613';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Colectivo de Abogados José Alvear Restrepo - CAJAR|Comisión Colombiana de Juristas - CCJ' where codigo='748-CI-00631';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=69, remitente_nombre='Universidad Industrial de Santander - UIS' where codigo='748-CI-00635';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-00636';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='748-CI-00641';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=72, remitente_nombre='Ejército Nacional de Colombia' where codigo='748-CI-00642';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Centro de Investigación y Educación Popular - CINEP' where codigo='748-CI-00643';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=19762, remitente_nombre='Asociación Nuevas Esperanzas del Municipio de Puerto Asís' where codigo='748-CI-00646';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Corporación Jurídica Libertad' where codigo='748-CI-00647';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Humanidad Vigente Corporación Jurídica' where codigo='748-CI-00650';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00674';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00675';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00676';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00677';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00678';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00679';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00680';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00681';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00682';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00683';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00684';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00685';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00686';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00687';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00688';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00689';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00690';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00691';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00692';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00693';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00694';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00695';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00696';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00697';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00698';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00699';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00700';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00701';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00702';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00703';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00704';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00705';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Fundación Progresar' where codigo='748-CI-00707';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00709';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00710';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00711';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00712';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00713';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00716';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00717';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00718';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00719';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00720';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Consultoría para los Derechos Humanos y el Desplazamiento - CODHES' where codigo='119-CI-00721';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00722';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00723';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00724';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00725';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00726';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00727';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00728';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00729';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00730';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00731';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00732';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00733';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00734';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00735';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00736';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Corporación Fuerza de Paz - CORFUPAZ' where codigo='119-CI-00737';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00738';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00739';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00740';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5541, remitente_nombre='Sindicato de Trabajadores Oficiales y Empleados Públicos de los Municipios del Departamento de Antioquia – SINTRAOFAN' where codigo='119-CI-00741';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00742';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00743';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00744';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00746';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00747';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00748';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00749';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00750';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00751';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00752';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00753';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00755';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00756';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00757';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00758';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5538, remitente_nombre='Consejo Regional Indígena del Cauca - CRIC' where codigo='119-CI-00759';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5536, remitente_nombre='Familiares de caminantes víctimas Masacre Puracé' where codigo='119-CI-00760';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00761';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00762';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00763';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00764';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5535, remitente_nombre='Ruta Pacífica de las Mujeres' where codigo='119-CI-00765';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5535, remitente_nombre='Ruta Pacífica de las Mujeres' where codigo='119-CI-00766';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Fundación Forjando Futuros' where codigo='119-CI-00767';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00768';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00769';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-00770';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Colectivo Sociojurídico Orlando Fals Borda - COLECTIVO OFB|Colectivo de Abogados José Alvear Restrepo – CAJAR|Comisión Intereclesial de Justicia y Paz' where codigo='748-CI-00775';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5536, remitente_nombre='Grupo de Víctimas de Misión Medica Norte de Santander' where codigo='748-CI-00788';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Centro de Estudios de Derecho, Justicia y Sociedad - DEJUSTICIA' where codigo='748-CI-00796';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5537, remitente_nombre='Colectivo de Guardaparques de Colombia' where codigo='748-CI-00797';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=69, remitente_nombre='Archivo Memorial de la Víctimas - AMOVI' where codigo='748-CI-00854';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Procuraduría General de la Nación' where codigo='748-CI-00886';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Fundación Cultura Democrática - FUCUDE' where codigo='365-CI-00936';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Fundación Brigada Jurídica Eduardo Umaña Mendoza' where codigo='365-CI-00938';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5536, remitente_nombre='Mesa Regional de Organizaciones Sociales del Putumayo, Baja Bota Caucana y Cofanía Jardínes de Sucumbíos (NAR) - MEROS|Mesas Municipales de Víctimas del Medio y Bajo Putumayo' where codigo='066-CI-00948';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-00951';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=69, remitente_nombre='Archivo Memorial de la Víctimas - AMOVI|Universidad Industrial de Santander - UIS' where codigo='365-CI-00971';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=69, remitente_nombre='Archivo Memorial de la Víctimas - AMOVI|Universidad Industrial de Santander - UIS' where codigo='365-CI-00979';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Comisión Colombiana de Juristas - CCJ' where codigo='365-CI-00984';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5535, remitente_nombre='Asociación de Mujeres - AINI' where codigo='365-CI-00995';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Asociación para la Promoción Social Alternativa - MINGA' where codigo='365-CI-00996';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Asociación para la Promoción Social Alternativa - MINGA' where codigo='365-CI-00997';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Asociación para la Promoción Social Alternativa - MINGA' where codigo='365-CI-00998';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Asociación CODEBAC ONG' where codigo='365-CI-01003';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=69, remitente_nombre='Archivo Memorial de la Víctimas - AMOVI|Universidad Industrial de Santander - UIS|Movimiento Nacional de Víctimas de Crímenes de Estado - MOVICE' where codigo='365-CI-01007';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5538, remitente_nombre='Cabildo Indígena del resguardo Kankuamo' where codigo='205-CI-01013';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01028';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01029';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01030';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01031';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01032';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01033';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01034';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01035';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01037';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01038';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5536, remitente_nombre='Organización Madres de Falsos Positivos Suacha y Bogotá – MAFAPO' where codigo='119-CI-01039';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=19762, remitente_nombre='Asociación Nacional de Usuarios Campesinos - ANUC' where codigo='119-CI-01040';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01041';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01042';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01043';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01044';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01045';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01046';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01047';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01049';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01050';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01051';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01052';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5535, remitente_nombre='Movimiento de Mujeres Yo Puedo' where codigo='119-CI-01053';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Centro de Estudios de Derecho, Justicia y Sociedad - DEJUSTICIA' where codigo='119-CI-01057';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01059';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01060';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01061';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01062';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01063';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01064';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01065';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01066';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01067';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01070';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01072';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01083';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Colectivo Sociojurídico Orlando Fals Borda - COLECTIVO OFB' where codigo='365-CI-01118';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Centro de Estudios de Derecho, Justicia y Sociedad - DEJUSTICIA' where codigo='066-CI-01168';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01174';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01175';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01176';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5538, remitente_nombre='Cabildo Indígena Nasa Kitek Kiwe NEEH WE SX' where codigo='066-CI-01178';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Centro Nacional de Memoria Histórica - CNMH' where codigo='365-CI-01181';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Corporación Regional Para la Defensa de los Derechos Humanos - CREDHOS' where codigo='180-CI-01205';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Víctimas de los Fondos Privados de Pensiones' where codigo='365-CI-01209';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01210';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01213';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01214';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01215';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01216';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01217';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01218';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01272';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01275';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01276';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01279';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01280';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01281';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01282';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01284';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01285';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01286';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01287';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5542, remitente_nombre='Programa Somos Defensores - Programa No Gubernamental de Protección a Defensores de Derechos Humanos - PNGPDDH' where codigo='365-CI-01290';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5536, remitente_nombre='Asociación de Víctimas Unidas de Granada - Asovida' where codigo='365-CI-01291';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Fundación de Derechos Humanos Joel Sierra - FDHJS' where codigo='744-CI-01295';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01297';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01298';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01299';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01300';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01301';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01305';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01308';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5536, remitente_nombre='Colectivo de Mujeres Víctimas Máscaras de la Verdad' where codigo='365-CI-01333';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Colectivo Sociojurídico Orlando Fals Borda - COLECTIVO OFB' where codigo='365-CI-01339';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01363';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01429';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01457';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01459';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5536, remitente_nombre='Cultura Democrática Colectivo de víctimas de la Masacre La Chinita' where codigo='365-CI-01516';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01549';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01551';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01552';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01554';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01557';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01558';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01572';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01573';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01574';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01575';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01576';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01577';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5536, remitente_nombre='Mesa Municipal de Participación Efectiva de Víctimas de Medellín' where codigo='066-CI-01578';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01582';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01584';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01676';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5534, remitente_nombre='Derechos con Dignidad S.A.S.' where codigo='1304-CI-01685';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01695';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5541, remitente_nombre='Asociación Mutual De Mineros "El Cogote"' where codigo='365-CI-01696';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01702';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01711';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01712';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01713';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01714';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01715';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01716';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01717';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='823-CI-01728';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01737';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01738';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01739';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01740';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01741';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5536, remitente_nombre='Movimiento Nacional de Víctimas de Crímenes de Estado - MOVICE' where codigo='1306-CI-01747';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5535, remitente_nombre='Red de Mujeres Víctimas y Profesionales' where codigo='066-CI-01752';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01753';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01754';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01755';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01756';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='066-CI-01757';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1306-CI-01758';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01767';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01768';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01769';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01770';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01771';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01772';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01773';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01774';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01775';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01776';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01777';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01778';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01779';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01780';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01781';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01782';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01783';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01784';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01785';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01786';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01790';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01791';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01792';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01793';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01794';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01795';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01796';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01797';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01798';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01799';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01800';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01802';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01803';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01804';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01805';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01806';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01807';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01808';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01810';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01811';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01812';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01813';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01814';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01815';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01817';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5536, remitente_nombre='Familiares Europa y Abya Yala Desaparecidos En Colombia' where codigo='1308-CI-01818';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01819';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01820';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01824';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01826';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01830';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01831';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01832';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01833';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01835';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01836';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01837';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01838';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01839';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01840';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01841';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01843';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01844';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01845';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01846';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01847';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='365-CI-01848';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01849';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=5538, remitente_nombre='Red de Consejos Comunitarios del Caribe - REDECOM' where codigo='1266-CI-01850';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01851';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01852';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01854';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1308-CI-01856';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01861';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01862';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01863';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01864';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01865';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01866';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01867';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01870';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01871';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01872';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1266-CI-01873';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='086-CI-01929';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01934';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01935';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01936';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01937';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01938';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01939';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01940';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01941';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01942';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01943';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01944';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01945';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01946';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01947';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01948';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01949';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01950';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01951';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01952';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01953';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01954';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01955';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01956';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01957';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01958';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01959';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01960';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01961';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01962';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01963';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01964';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01965';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01966';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01967';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01968';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01969';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01970';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01971';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01972';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01973';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01974';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01975';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01976';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01977';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01978';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01979';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01980';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01981';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='119-CI-01982';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1434-CI-01997';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1434-CI-01998';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1434-CI-01999';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1434-CI-02000';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1434-CI-02001';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1434-CI-02002';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1434-CI-02003';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1434-CI-02004';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1434-CI-02005';
update esclarecimiento.casos_informes set remitente_id_tipo_organizacion=75, remitente_nombre='Jurisdicción Especial para la Paz - JEP' where codigo='1434-CI-02006';